name: Deploy Infrastructure

on: workflow_dispatch

jobs:
  set-environment:
    name: Set environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS region
        run: echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Set environment
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Set service name
        run: echo "SERVICE_NAME=website" >> $GITHUB_ENV

      - name: Set subdomain
        run: |
          if [ "$ENVIRONMENT" == "production" ]; then
            echo "SUBDOMAIN=www" >> $GITHUB_ENV
          else
            echo "SUBDOMAIN=$ENVIRONMENT" >> $GITHUB_ENV
          fi

      - name: Set domain
        run: echo "DOMAIN=kuwabuga.com" >> $GITHUB_ENV

      - name: Set redirect
        run: echo "REDIRECT=$SUBDOMAIN.$DOMAIN" >> $GITHUB_ENV

    outputs:
      AWS_REGION: ${{ env.AWS_REGION }}
      ENVIRONMENT: ${{ env.ENVIRONMENT }}
      SERVICE_NAME: ${{ env.SERVICE_NAME }}
      SUBDOMAIN: ${{ env.SUBDOMAIN }}
      DOMAIN: ${{ env.DOMAIN }}
      REDIRECT: ${{ env.REDIRECT }}

  configure-website:
    name: Configure AWS S3 website
    needs: [set-environment]
    uses: Kuwabuga/configure-aws-s3-website/.github/workflows/deploy_website.yml@production
    with:
      AWS_REGION: ${{ needs.set-environment.outputs.AWS_REGION }}
      ENVIRONMENT: ${{ needs.set-environment.outputs.ENVIRONMENT }}
      SERVICE_NAME: ${{ needs.set-environment.outputs.SERVICE_NAME }}
      SUBDOMAIN: ${{ needs.set-environment.outputs.SUBDOMAIN }}
      DOMAIN: ${{ needs.set-environment.outputs.DOMAIN }}

  configure-website-redirect:
    name: Configure AWS S3 website direct
    needs: [set-environment, configure-website]
    if: needs.set-environment.outputs.ENVIRONMENT == 'production'
    uses: Kuwabuga/configure-aws-s3-website/.github/workflows/deploy_redirect.yml@production
    with:
      AWS_REGION: ${{ needs.set-environment.outputs.AWS_REGION }}
      ENVIRONMENT: ${{ needs.set-environment.outputs.ENVIRONMENT }}
      SERVICE_NAME: ${{ needs.set-environment.outputs.SERVICE_NAME }}
      SUBDOMAIN: ${{ needs.set-environment.outputs.SUBDOMAIN }}
      DOMAIN: ${{ needs.set-environment.outputs.DOMAIN }}
      REDIRECT: ${{ needs.set-environment.outputs.REDIRECT }}