name: Run Website's Unit and E2E tests

on:
  pull_request:
    paths:
      - "**"
  push:
    paths:
      - "**"

jobs:

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      # TODO
      # - name: Run unit tests
      #   run: npm run test:unit

  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      # TODO
      # - name: Run e2e tests
      #   run: npm run test:e2e
