name: Run Website's Unit and E2E tests

on:
  pull_request:
    paths: 
      - "**"
  push:
    paths:
      - "application/**"

env:
  APPLICATION_DIRECTORY: "./application"

jobs:

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm install

      - name: Run unit tests
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm run test:unit

  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm install

      - name: Run e2e tests
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: npm run test:e2e
